import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "@/app/globals.css";
import Header from "@/components/global/Header";
import Footer from "@/components/global/Footer";
import { getCurrentUser } from "@/lib/auth";
import { ThemeProvider } from "../providers/ThemeProvider";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  return (
    <html
      lang="en"
      className={`${fontSans.variable} ${fontSans.variable} h-full antialiased`}
    >
      <body className="min-h-full">
        <NextTopLoader color="#ffffff" height={4} showSpinner={false} />
        <div className="flex min-h-screen flex-col bg-background text-foreground">
          <ThemeProvider>
            <Header user={user?.data} />
            <main className="flex-1">
              {children}
            </main>
            <Footer />
            <Toaster position="top-right" richColors />
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
