import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "@/app/globals.css";
import { ThemeProvider } from "../providers/ThemeProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { DashboardNav } from "@/components/dashboard/dashboard-nav";
import { DashboardHeader } from "@/components/dashboard/dashboard-header";
import { Toaster } from "sonner";
import { DashboardSidebar } from "@/components/dashboard/dashboard-sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import { getCurrentUser } from "@/lib/auth";
import NextTopLoader from "nextjs-toploader";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  return (
    <html
      lang="en"
      className={`${fontSans.variable} ${fontSans.variable} h-full antialiased`}
    >
      <body>
        <NextTopLoader color="#ffffff" height={4} showSpinner={false} />
        <ThemeProvider>
          <TooltipProvider >
            <SidebarProvider>
              <div className="flex h-screen w-full bg-muted/10">
                <DashboardSidebar />
                <div className="flex-1 flex flex-col overflow-hidden">
                  <DashboardHeader user={user?.data} />
                  <main className="flex-1 overflow-y-auto p-6">
                    {children}
                  </main>
                </div>
              </div>
            </SidebarProvider>
            <Toaster position="top-right" richColors />
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
